const employees = [
  {
    id: 1,
    firstName: "Rahul",
    email: "e1@e.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        title: "Prepare Report",
        description: "Complete the monthly sales report",
        date: "2025-09-03",
        category: "Work",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Team Meeting",
        description: "Attend the project kickoff meeting",
        date: "2025-09-04",
        category: "Meeting",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Client Email",
        description: "Send project update to client",
        date: "2025-09-05",
        category: "Communication",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    firstName: "Ankit",
    email: "employee2@example.com",
    password: "123",
    taskCount: {
      active: 3,
      newTask: 2,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        title: "Code Review",
        description: "Review pull requests for frontend repo",
        date: "2025-09-03",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Bug Fix",
        description: "Resolve login page validation issue",
        date: "2025-09-04",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Knowledge Sharing",
        description: "Prepare slides for weekly tech talk",
        date: "2025-09-06",
        category: "Training",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Unit Testing",
        description: "Write test cases for new API endpoints",
        date: "2025-09-07",
        category: "Testing",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    firstName: "Sneha",
    email: "employee3@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        title: "UI Design",
        description: "Design mockups for new dashboard",
        date: "2025-09-03",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Prototype Testing",
        description: "Test the Figma prototype with users",
        date: "2025-09-05",
        category: "Design",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Feedback Review",
        description: "Analyze feedback from last sprint demo",
        date: "2025-09-06",
        category: "Analysis",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    firstName: "Vikram",
    email: "employee4@example.com",
    password: "123",
    taskCount: {
      active: 3,
      newTask: 2,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        title: "Server Setup",
        description: "Configure staging server",
        date: "2025-09-03",
        category: "Infrastructure",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Database Migration",
        description: "Migrate database to new version",
        date: "2025-09-04",
        category: "Database",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Backup Check",
        description: "Verify daily backups",
        date: "2025-09-05",
        category: "Maintenance",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Monitoring Setup",
        description: "Add monitoring for new microservice",
        date: "2025-09-06",
        category: "Monitoring",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    firstName: "Priya",
    email: "employee5@example.com",
    password: "123",
    taskCount: {
      active: 3,
      newTask: 2,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        title: "Recruitment Drive",
        description: "Conduct interviews for new developers",
        date: "2025-09-03",
        category: "HR",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Onboarding",
        description: "Guide new hires through onboarding",
        date: "2025-09-04",
        category: "HR",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Policy Update",
        description: "Update leave policy document",
        date: "2025-09-05",
        category: "HR",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Team Building",
        description: "Organize team-building activity",
        date: "2025-09-06",
        category: "HR",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 101,
    firstName: "admin",
    email: "admin@example.com",
    password: "123",
  },
];

export const setlocalStrorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};
export const getlocalStrorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
